In [24]:
import random
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

## Blobs

In [25]:
def f(x):
    # y = mx + b
    return 0.3*x + 0.2


class Point:
    def __init__(self, width, height):
        self.x = np.random.uniform(-1, 1, width)
        self.y = np.random.uniform(-1, 1, height)
        self.bias = 1
        self.labels = []
    
    def point(self):
        for x, y in zip(self.x, self.y):
            lineY = f(x)
            if y > lineY:
                self.labels.append(1)
            else:
                self.labels.append(-1)

        return self.labels


points = Point(500, 500)
labels = points.point()
x = points.x
y = points.y
inputs = pd.DataFrame({'x':x, 'y':y})

# NeuralNetwork

In [26]:
class NeuralNetwork:
    def __init__(self, numInput, numHidden, numOutput):
        self.lr = 0.1
        self.input_nodes = numInput
        self.hidden_nodes = numHidden
        self.output_nodes = numOutput

        self.weights_ih = np.random.uniform(-1, 1, (self.hidden_nodes, self.input_nodes))
        self.weights_ho = np.random.uniform(-1, 1, (self.output_nodes, self.hidden_nodes))

        self.bias_h = np.random.uniform(-1, 1, (self.hidden_nodes, 1))
        self.bias_o = np.random.uniform(-1, 1, (self.output_nodes, 1))

    def sigmoid(self, x):
        return 1/(1 + np.exp(-x))

    def dsigmoid(self, x):
        return x * (1 - x)

    
    def feed_forward(self, inputs):
        inputs = np.array(inputs)
        # HIDDEN LAYER
        self.hidden_sum = np.matmul(self.weights_ih, np.transpose(inputs)) + self.bias_h
        self.hidden_out = self.sigmoid(self.hidden_sum)
        # OUTPUT LAYER
        self.output_sum = np.matmul(self.weights_ho, self.hidden_out) + self.bias_o
        self.output_out = self.sigmoid(self.output_sum)

        return np.transpose(self.output_out)

    
    def train(self, inputs, targets):
        targets = np.array(targets).reshape(1, -1)
        inputs = np.array(inputs)

        self.feed_forward(inputs)

        # Calculate the output deltas
        output_deltas = (targets - self.output_out) * self.dsigmoid(self.output_out)

        # Hidden layer errors and deltas
        hidden_errors = np.matmul(self.weights_ho.T, output_deltas)
        hidden_deltas = hidden_errors * self.dsigmoid(self.hidden_out)

        # Update weights
        self.weights_ho += self.lr * np.matmul(output_deltas, self.hidden_out.T)
        self.weights_ih += self.lr * np.matmul(hidden_deltas, inputs)
        # Bias weights
        self.bias_h += self.lr * np.sum(hidden_deltas, axis=1, keepdims=True)
        self.bias_o += self.lr * np.sum(output_deltas, axis=1, keepdims=True)

In [27]:
nn = NeuralNetwork(2, 2, 1)

#### Weights

In [28]:
nn.weights_ih

array([[ 0.43059455, -0.38813487],
       [-0.17057422, -0.54657708]])

In [29]:
nn.weights_ho

array([[-0.77674616, -0.60948148]])

## Feed Forward Check

In [30]:
nn.feed_forward(inputs.iloc[0])

array([[0.41707343],
       [0.46852766]])

In [31]:
nn.feed_forward(inputs)

array([[0.44032028],
       [0.4111336 ],
       [0.41624369],
       [0.4074687 ],
       [0.4481278 ],
       [0.40884985],
       [0.43782781],
       [0.4388135 ],
       [0.40841579],
       [0.43228857],
       [0.43624116],
       [0.41385094],
       [0.46293737],
       [0.40898499],
       [0.41194115],
       [0.42596223],
       [0.43464601],
       [0.43655772],
       [0.38487397],
       [0.39726328],
       [0.41113232],
       [0.408387  ],
       [0.42734612],
       [0.40799875],
       [0.40558551],
       [0.41323205],
       [0.46509504],
       [0.41805701],
       [0.41994118],
       [0.45015782],
       [0.41273662],
       [0.40832444],
       [0.41000301],
       [0.40939041],
       [0.40719066],
       [0.458785  ],
       [0.39958832],
       [0.42860649],
       [0.40731236],
       [0.45327689],
       [0.38762167],
       [0.4532344 ],
       [0.42100249],
       [0.42694445],
       [0.41288214],
       [0.42449943],
       [0.38830084],
       [0.444

## Train 

In [32]:
nn.train(inputs, labels)

Worked!

#### Test

In [33]:
preds = nn.feed_forward(inputs)

In [34]:
inputs, labels, preds

(            x         y
 0    0.978827  0.686267
 1   -0.288717 -0.596618
 2    0.574337 -0.153159
 3    0.416437 -0.446687
 4   -0.567506  0.350249
 ..        ...       ...
 495 -0.338001  0.705242
 496 -0.197100  0.803076
 497  0.254890  0.805971
 498 -0.608593 -0.874647
 499  0.929628  0.030993
 
 [500 rows x 2 columns],
 [1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
  1,
  -1,
  -1,
  1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
  1,
  1,
  1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
  1,
  -1,
  1,
  -1,
  -1,
  1,
  -1,
  -1,
  1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  -1,
  -1,
  -1,
  1,
  -1,
  -1,
  -1,
  -1,
  1,
  -1,
  1,
  1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  -1,
  -1,
  1,
  1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  -1,
  -1

In [35]:
             # 2x500                  # 500x2               # 4x4
nn.dsigmoid(nn.hidden_out) @ np.transpose(nn.hidden_out)

array([[58.23923462, 56.50753024],
       [63.603678  , 61.0671649 ]])

In [36]:
nn = NeuralNetwork(2, 2, 1)

In [37]:
xor = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 0],
    [0, 0, 0]
])

for i in range(100000):
    np.random.shuffle(xor)
    xor_inputs = np.array(xor[:, :2])
    xor_labels = np.array(xor[:, 2:3]).reshape(4)

    nn.train(xor_inputs, xor_labels)

In [38]:
xor = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 0],
    [0, 0, 0]
])

In [39]:
print(f"Inputs: {xor_inputs}")
print(f"Labels: {xor_labels}")
nn.feed_forward(xor_inputs)

Inputs: [[1 0]
 [0 1]
 [0 0]
 [1 1]]
Labels: [1 1 0 0]


array([[0.98896726],
       [0.98668222],
       [0.01166052],
       [0.0104078 ]])